name: Sync to Gitee

on: [ push, delete ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:dream2023/super-antd.git
          destination-repo: git@gitee.com:dream2023/super-antd.git
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: dream2023
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: dream2023/super-antd
          branch: main