name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      # - run: yarn test:coverage
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     files: ./coverage/clover.xml
      #     directory: ./coverage/lcov-report/
      #     name: codecov-umbrella
      #     fail_ci_if_error: true
      #     verbose: true
      - run: yarn docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-dist
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:dream2023/super-antd.git
          destination-repo: git@gitee.com:dream2023/super-antd.git
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: dream2023
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: dream2023/super-antd
          branch: main